# Production overrides for Docker Compose
version: '3.8'

services:
  postgres:
    restart: unless-stopped
    command: postgres -c 'max_connections=200'
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=lokr_prod_password

  redis:
    restart: unless-stopped
    volumes:
      - redis_data_prod:/data

  backend:
    restart: unless-stopped
    env_file:
      - .env.production
    volumes:
      - backend_storage_prod:/app/storage
    depends_on:
      - postgres
      - redis

  frontend:
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  nginx:
    restart: unless-stopped

volumes:
  postgres_data_prod:
    driver: local
  redis_data_prod:
    driver: local
  backend_storage_prod:
    driver: local